import { PrismaClient, Role, VacancyStatus } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding UzbJobs database with comprehensive Uzbekistan tech vacancies & companies...");

  // 1. System Settings
  await prisma.systemSetting.upsert({
    where: { key: "AUTO_APPROVE_THRESHOLD" },
    update: {},
    create: {
      key: "AUTO_APPROVE_THRESHOLD",
      value: "85",
      description: "Минимальный AI score для автоматической публикации без ручной модерации",
    },
  });

  await prisma.systemSetting.upsert({
    where: { key: "EMPLOYER_NOTIFICATION_MODE" },
    update: {},
    create: {
      key: "EMPLOYER_NOTIFICATION_MODE",
      value: "MANUAL",
      description: "Режим отправки уведомлений работодателям: OFF / MANUAL / AUTOMATIC",
    },
  });

  // 2. Admin user
  const hashedPassword = await bcrypt.hash("200220032013", 12);
  const adminUser = await prisma.user.upsert({
    where: { email: "inogomovfozil01@gmail.com" },
    update: {
      password: hashedPassword,
      role: Role.ADMIN,
    },
    create: {
      email: "inogomovfozil01@gmail.com",
      name: "Fozil Inogomov (Admin)",
      password: hashedPassword,
      role: Role.ADMIN,
      profile: {
        create: {
          headline: "Platform Owner & Administrator",
          bio: "Администратор и владелец платформы UzbJobs",
          city: "Ташкент",
          skills: ["Management", "AI Pipelines", "Fullstack", "DevOps"],
        },
      },
    },
  });
  console.log(`👤 Admin created/updated: ${adminUser.email}`);

  // 3. Search Queries for AI Scanner
  const queries = [
    { query: "Frontend Developer Tashkent", category: "IT / Software", location: "Ташкент", priority: 10 },
    { query: "Backend Developer Uzbekistan", category: "IT / Software", location: "Узбекистан", priority: 10 },
    { query: "Python Developer Tashkent", category: "IT / Software", location: "Ташкент", priority: 9 },
    { query: "JavaScript Developer Uzbekistan", category: "IT / Software", location: "Узбекистан", priority: 9 },
    { query: "React Developer Uzbekistan", category: "IT / Software", location: "Узбекистан", priority: 8 },
    { query: "Golang Developer Tashkent", category: "IT / Software", location: "Ташкент", priority: 9 },
    { query: "Designer Tashkent", category: "Design", location: "Ташкент", priority: 7 },
    { query: "QA Engineer Uzbekistan", category: "IT / Software", location: "Узбекистан", priority: 7 },
    { query: "DevOps Engineer Tashkent", category: "DevOps", location: "Ташкент", priority: 8 },
    { query: "Flutter Developer Uzbekistan", category: "Mobile", location: "Ташкент", priority: 8 },
    { query: "Remote job Uzbekistan", category: "Remote", location: "Удаленно", priority: 9 },
    { query: "Data Engineer Uzbekistan", category: "Data Science", location: "Узбекистан", priority: 6 },
  ];

  for (const q of queries) {
    await prisma.searchQuery.upsert({
      where: { query: q.query },
      update: {},
      create: {
        query: q.query,
        category: q.category,
        location: q.location,
        priority: q.priority,
        isActive: true,
      },
    });
  }
  console.log(`🔍 Created/updated ${queries.length} active search queries for scanner`);

  // 4. Search Sources
  const sources = [
    { name: "HeadHunter Uzbekistan", domain: "hh.uz", trustScore: 95 },
    { name: "LinkedIn", domain: "linkedin.com", trustScore: 90 },
    { name: "Rabota.uz", domain: "rabota.uz", trustScore: 85 },
    { name: "OLX Uzbekistan", domain: "olx.uz", trustScore: 70 },
  ];

  for (const s of sources) {
    await prisma.searchSource.upsert({
      where: { domain: s.domain },
      update: {},
      create: {
        name: s.name,
        domain: s.domain,
        trustScore: s.trustScore,
        isActive: true,
      },
    });
  }

  // 5. Companies in Uzbekistan
  const companiesData = [
    {
      name: "Uzum Technologies",
      slug: "uzum-technologies",
      description: "Ведущая экосистема цифровых сервисов Узбекистана: национальный маркетплейс Uzum Market, финтех Uzum Bank и сервис экспресс-доставки Uzum Tezkor.",
      city: "Ташкент",
      website: "https://uzum.com",
      isVerified: true,
    },
    {
      name: "Payme",
      slug: "payme-uz",
      description: "Крупнейший платежный сервис Узбекистана для мгновенных онлайн-платежей, переводов с карты на карту и финансовых решений для B2B.",
      city: "Ташкент",
      website: "https://payme.uz",
      isVerified: true,
    },
    {
      name: "EPAM Uzbekistan",
      slug: "epam-uzbekistan",
      description: "Международный поставщик услуг по разработке цифровых платформ, сложного программного обеспечения и консалтинга с офисами в Ташкенте и Самарканде.",
      city: "Ташкент",
      website: "https://epam.com",
      isVerified: true,
    },
    {
      name: "CLICK",
      slug: "click-uz",
      description: "Первопроходец мобильного банкинга в Узбекистане. Финтех-платформа с миллионами активных пользователей и экосистемой сервисов CLICK Up.",
      city: "Ташкент",
      website: "https://click.uz",
      isVerified: true,
    },
    {
      name: "TBC Bank Uzbekistan",
      slug: "tbc-bank-uz",
      description: "Первый полностью цифровой необанк в Узбекистане, входящий в состав международной группы TBC Bank Group с передовыми стандартами разработки.",
      city: "Ташкент",
      website: "https://tbcbank.uz",
      isVerified: true,
    },
    {
      name: "Yandex Uzbekistan",
      slug: "yandex-uzbekistan",
      description: "Центр разработки и развития городских и логистических сервисов Yandex Go, Yandex Delivery, Edadeal и навигационных технологий в Центральной Азии.",
      city: "Ташкент",
      website: "https://yandex.uz",
      isVerified: true,
    },
    {
      name: "Beeline Uzbekistan (Unitel)",
      slug: "beeline-uzbekistan",
      description: "Один из ведущих телекоммуникационных операторов страны, развивающий экосистему цифровых продуктов, FinTech и облачные решения.",
      city: "Ташкент",
      website: "https://beeline.uz",
      isVerified: true,
    },
    {
      name: "Anorbank",
      slug: "anorbank-uz",
      description: "Первый отечественный цифровой коммерческий банк без физических отделений, предоставляющий полный спектр финансовых услуг онлайн.",
      city: "Ташкент",
      website: "https://anorbank.uz",
      isVerified: true,
    },
    {
      name: "IT Park Uzbekistan",
      slug: "it-park-uzbekistan",
      description: "Главный технопарк и технологический драйвер Узбекистана, объединяющий стартапы, резидентов, IT-академии и международные компании.",
      city: "Ташкент",
      website: "https://it-park.uz",
      isVerified: true,
    },
    {
      name: "Billz",
      slug: "billz-io",
      description: "Быстрорастущая SaaS-платформа для ритейла и автоматизации торговли в Центральной Азии (POS, аналитика, CRM, управление складом).",
      city: "Ташкент",
      website: "https://billz.io",
      isVerified: true,
    },
    {
      name: "Mad Devs Central Asia",
      slug: "mad-devs-ca",
      description: "Инженерная компания, специализирующаяся на разработке высоконагруженных бэкендов, облачной архитектуре и DevOps для глобальных клиентов.",
      city: "Ташкент",
      website: "https://maddevs.io",
      isVerified: true,
    },
    {
      name: "Exadel Uzbekistan",
      slug: "exadel-uzbekistan",
      description: "Глобальная IT-компания, разрабатывающая корпоративное ПО, решения в области AI, тестирования и облачных платформ с хабом в Самарканде.",
      city: "Самарканд",
      website: "https://exadel.com",
      isVerified: true,
    },
    {
      name: "Kapitalbank",
      slug: "kapitalbank-uz",
      description: "Крупнейший частный коммерческий банк Узбекистана с активным развитием интернет-банкинга, мобильных продуктов и розничных цифровых сервисов.",
      city: "Ташкент",
      website: "https://kapitalbank.uz",
      isVerified: true,
    },
    {
      name: "Ucell (Coscom)",
      slug: "ucell-uz",
      description: "Один из лидеров рынка сотовой связи Узбекистана, активно инвестирующий в развертывание сетей 5G и корпоративные цифровые продукты.",
      city: "Андижан",
      website: "https://ucell.uz",
      isVerified: true,
    },
    {
      name: "MyUztelecom (Uztelecom)",
      slug: "uztelecom-uz",
      description: "Национальный оператор связи Узбекистана, управляющий крупнейшей магистральной сетью, дата-центрами и телеком-инфраструктурой страны.",
      city: "Ташкент",
      website: "https://uztelecom.uz",
      isVerified: true,
    },
  ];

  const companies: Record<string, any> = {};
  for (const c of companiesData) {
    const comp = await prisma.company.upsert({
      where: { slug: c.slug },
      update: {
        description: c.description,
        city: c.city,
        website: c.website,
        isVerified: c.isVerified,
      },
      create: c,
    });
    companies[c.slug] = comp;
  }
  console.log(`🏢 Created/updated ${companiesData.length} companies across Uzbekistan`);

  // 6. Comprehensive Realistic Vacancies
  const sampleVacancies = [
    // --- Uzum Technologies ---
    {
      title: "Senior Frontend Developer (React / Next.js)",
      slug: "senior-frontend-developer-react-nextjs-uzum",
      companyId: companies["uzum-technologies"].id,
      companyName: companies["uzum-technologies"].name,
      description:
        "Мы ищем опытного Senior Frontend разработчика в команду маркетплейса Uzum Market. Вам предстоит проектировать архитектуру клиентских приложений с миллионной аудиторией, оптимизировать Core Web Vitals (LCP, INP) и работать с современным стеком Next.js, TypeScript и GraphQL.",
      shortDescription: "Разработка высоконагруженного интерфейса маркетплейса Uzum Market на React и Next.js.",
      salaryMin: 2500,
      salaryMax: 4000,
      salaryCurrency: "USD",
      salaryText: "$2,500 – $4,000",
      location: "Ташкент, Мирабадский район",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: false,
      skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "GraphQL", "Redux Toolkit", "CI/CD"],
      requirements: [
        "Опыт коммерческой разработки на React от 4 лет",
        "Глубокие знания JavaScript, TypeScript и современного веб-стандарта",
        "Опыт SSR/SSG в Next.js и оптимизации производительности интерфейсов",
        "Понимание микрофронтендов и дизайн-систем",
      ],
      responsibilities: [
        "Разработка и поддержка ключевых витринных модулей Uzum Market",
        "Проведение Code Review и менторинг разработчиков",
        "Взаимодействие с UI/UX дизайнерами и Backend-командой",
      ],
      benefits: [
        "Конкурентная зарплата с привязкой к доллару США",
        "ДМС со стоматологией для сотрудника и членов семьи",
        "Современный офис в центре Ташкента с зонами отдыха и кофе-поинтами",
        "Бюджет на обучение и участие в международных IT-конференциях",
      ],
      sourceUrl: "https://uzum.com/careers/senior-frontend",
      sourceNormalizedUrl: "https://uzum.com/careers/senior-frontend",
      sourceName: "Uzum Careers",
      qualityScore: 96,
      relevanceScore: 98,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },
    {
      title: "Lead Golang Backend Engineer (Highload Services)",
      slug: "lead-golang-backend-engineer-uzum",
      companyId: companies["uzum-technologies"].id,
      companyName: companies["uzum-technologies"].name,
      description:
        "Команда сервиса логистики и процессинга заказов Uzum Tezkor ищет тимлида/ведущего Golang инженера. Задача — развивать сервис диспетчеризации курьеров, маршрутизацию в реальном времени и распределенную обработку заказов с нагрузкой свыше 15 000 RPS.",
      shortDescription: "Разработка распределенного бэкенда логистики Uzum на Go и Kafka.",
      salaryMin: 3500,
      salaryMax: 5000,
      salaryCurrency: "USD",
      salaryText: "$3,500 – $5,000",
      location: "Ташкент, ул. Нукусская",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Lead",
      isRemote: false,
      skills: ["Go", "Golang", "PostgreSQL", "Kafka", "Redis", "gRPC", "Kubernetes", "Highload"],
      requirements: [
        "Опыт разработки на Go от 5 лет в высоконагруженных системах",
        "Практика проектирования событийно-ориентированной архитектуры (Event-driven)",
        "Глубокое понимание concurrency, memory management и профилирования Go приложений (pprof)",
        "Опыт руководства инженерной группой от 4 человек",
      ],
      responsibilities: [
        "Архитектурное руководство разработкой микросервисов",
        "Обеспечение SLA 99.98% и оптимизация задержек (low latency)",
        "Формирование технических стандартов и найм сильных инженеров",
      ],
      benefits: [
        "Опционная программа для ключевых сотрудников",
        "Премиальное медицинское страхование",
        "Компенсация парковки и фитнеса",
      ],
      sourceUrl: "https://uzum.com/careers/lead-go",
      sourceNormalizedUrl: "https://uzum.com/careers/lead-go",
      sourceName: "Uzum Careers",
      qualityScore: 98,
      relevanceScore: 99,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },
    {
      title: "Product Manager (E-commerce / Мобильные приложения)",
      slug: "product-manager-ecommerce-uzum",
      companyId: companies["uzum-technologies"].id,
      companyName: companies["uzum-technologies"].name,
      description:
        "Ищем опытного Product Manager для развития клиентского мобильного приложения Uzum Market. Вам предстоит управлять бэклогом продуктовых гипотез, повышать конверсию в покупку (CVR) и средний чек, работая в тесной связке с командой UX-исследователей и дата-сайентистов.",
      shortDescription: "Развитие мобильного приложения Uzum Market и ключевых воронок продаж.",
      salaryMin: 22000000,
      salaryMax: 35000000,
      salaryCurrency: "UZS",
      salaryText: "22 000 000 – 35 000 000 сум",
      location: "Ташкент",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["Product Management", "A/B Testing", "Unit Economics", "Amplitude", "SQL", "Scrum"],
      requirements: [
        "Опыт работы Product Manager в B2C e-commerce или фудтехе от 2.5 лет",
        "Умение работать с метриками: Retention, LTV, CAC, CVR",
        "Навыки составления продуктовых требований (PRD) и проведения A/B тестов",
      ],
      responsibilities: [
        "Формирование и приоритизация дорожной карты продукта (Product Roadmap)",
        "Анализ пользовательских путей и поиск точек роста конверсий",
        "Синхронизация между бизнесом, дизайном и разработкой",
      ],
      benefits: [
        "Бонусы по результатам выполнения квартальных OKR",
        "Корпоративная скидка на все сервисы Uzum",
        "Программа ДМС",
      ],
      sourceUrl: "https://uzum.com/careers/product-manager",
      sourceNormalizedUrl: "https://uzum.com/careers/product-manager",
      sourceName: "Uzum Careers",
      qualityScore: 91,
      relevanceScore: 93,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Management",
    },

    // --- Payme ---
    {
      title: "Middle / Senior Python Developer (Fintech Core)",
      slug: "middle-senior-python-developer-fintech-payme",
      companyId: companies["payme-uz"].id,
      companyName: companies["payme-uz"].name,
      description:
        "Команда Payme расширяет инженерный состав для разработки сервисов мгновенных платежей и интеграции с международными банковскими шлюзами. Основной стек: Python 3.12, FastAPI, PostgreSQL, Redis, Kafka, Docker.",
      shortDescription: "Разработка высоконагруженных бэкенд-сервисов Payme на FastAPI и PostgreSQL.",
      salaryMin: 2000,
      salaryMax: 3500,
      salaryCurrency: "USD",
      salaryText: "$2,000 – $3,500",
      location: "Ташкент, Шайхантахурский район",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: true,
      skills: ["Python", "FastAPI", "PostgreSQL", "Redis", "Kafka", "Docker", "Asyncio"],
      requirements: [
        "Опыт разработки на Python от 3 лет",
        "Опыт работы с асинхронным кодом (asyncio, FastAPI)",
        "Уверенное знание реляционных баз данных и оптимизации сложных SQL запросов",
        "Опыт работы с очередями сообщений (Kafka или RabbitMQ)",
      ],
      responsibilities: [
        "Разработка микросервисов транзакционного процессинга",
        "Обеспечение отказоустойчивости 99.99% и защиты финансовых операций",
        "Написание модульных и интеграционных тестов",
      ],
      benefits: [
        "Гибридный или полностью удаленный формат работы по Узбекистану",
        "Официальное трудоустройство, прозрачные KPI",
        "Медицинская страховка и фитнес-компенсация",
        "Ноутбук MacBook Pro топовой конфигурации",
      ],
      sourceUrl: "https://payme.uz/careers/python-developer",
      sourceNormalizedUrl: "https://payme.uz/careers/python-developer",
      sourceName: "Payme Jobs",
      qualityScore: 94,
      relevanceScore: 95,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },
    {
      title: "Senior iOS Developer (Swift / SwiftUI)",
      slug: "senior-ios-developer-swift-payme",
      companyId: companies["payme-uz"].id,
      companyName: companies["payme-uz"].name,
      description:
        "Мы ищем сильного iOS разработчика, готового совершенствовать флагманское мобильное приложение Payme. Приложением пользуются миллионы людей каждый день, поэтому на первом плане безопасность, плавность 120 FPS и надежность архитектуры (Clean Swift / VIPER).",
      shortDescription: "Разработка флагманского мобильного приложения Payme для iOS.",
      salaryMin: 2500,
      salaryMax: 4200,
      salaryCurrency: "USD",
      salaryText: "$2,500 – $4,200",
      location: "Ташкент",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: true,
      skills: ["iOS", "Swift", "SwiftUI", "Combine", "VIPER", "Unit Testing", "CI/CD"],
      requirements: [
        "Коммерческий опыт разработки iOS приложений от 4 лет",
        "Глубокие знания Swift, памяти (ARC) и многопоточности (GCD/async-await)",
        "Опыт работы с безопасным хранением ключей (Keychain, Secure Enclave)",
        "Наличие опубликованных приложений в App Store",
      ],
      responsibilities: [
        "Разработка новых платежных фичей и интеграция биометрической аутентификации",
        "Оптимизация сетевого слоя и локального кэширования",
        "Участие в архитектурных дискуссиях мобильной гильдии",
      ],
      benefits: [
        "Работа в распределенной сильной команде",
        "Полное покрытие расходов на здоровье и спорт",
        "Ежегодный пересмотр заработной платы",
      ],
      sourceUrl: "https://payme.uz/careers/ios-engineer",
      sourceNormalizedUrl: "https://payme.uz/careers/ios-engineer",
      sourceName: "Payme Jobs",
      qualityScore: 95,
      relevanceScore: 96,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Mobile",
    },

    // --- EPAM Uzbekistan ---
    {
      title: "DevOps Engineer (Cloud Infrastructure - AWS & K8s)",
      slug: "devops-engineer-cloud-infrastructure-epam",
      companyId: companies["epam-uzbekistan"].id,
      companyName: companies["epam-uzbekistan"].name,
      description:
        "EPAM Uzbekistan приглашает DevOps инженера для построения надежной облачной инфраструктуры глобальных корпоративных заказчиков. Стек: AWS, Terraform, Kubernetes, Helm, GitLab CI, Prometheus, Grafana.",
      shortDescription: "Автоматизация CI/CD и поддержка Kubernetes кластеров в EPAM.",
      salaryMin: 1800,
      salaryMax: 3200,
      salaryCurrency: "USD",
      salaryText: "$1,800 – $3,200",
      location: "Ташкент / Самарканд",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: true,
      skills: ["DevOps", "AWS", "Kubernetes", "Terraform", "Docker", "GitLab CI", "Linux"],
      requirements: [
        "Опыт администрирования Linux систем от 3 лет",
        "Практический опыт работы с Kubernetes (EKS/GKE)",
        "Опыт написания Infrastructure as Code (Terraform)",
        "Английский язык на уровне B2 (разговорный)",
      ],
      responsibilities: [
        "Проектирование и масштабирование облачных сред",
        "Построение пайплайнов непрерывной доставки (CI/CD)",
        "Мониторинг, логирование и реагирование на инциденты",
      ],
      benefits: [
        "Международные проекты и релокационные программы",
        "Корпоративные курсы английского языка и сертификация AWS/GCP за счет компании",
        "Гибкий график и работа из дома",
      ],
      sourceUrl: "https://epam.com/careers/devops-tashkent",
      sourceNormalizedUrl: "https://epam.com/careers/devops-tashkent",
      sourceName: "EPAM Careers",
      qualityScore: 92,
      relevanceScore: 91,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "DevOps",
    },
    {
      title: "Senior Java / Spring Boot Engineer (Enterprise Systems)",
      slug: "senior-java-spring-boot-engineer-epam",
      companyId: companies["epam-uzbekistan"].id,
      companyName: companies["epam-uzbekistan"].name,
      description:
        "Ищем опытного Java разработчика в команду международных финтех и банковских систем. Проект связан с модернизацией легаси-решений в микросервисную архитектуру на базе Spring Cloud, Kafka, PostgreSQL и Docker.",
      shortDescription: "Разработка масштабируемых корпоративных бэкендов на Java 21 и Spring Boot.",
      salaryMin: 2500,
      salaryMax: 4200,
      salaryCurrency: "USD",
      salaryText: "$2,500 – $4,200",
      location: "Самарканд / Ташкент",
      city: "Самарканд",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: true,
      skills: ["Java", "Spring Boot", "Microservices", "PostgreSQL", "Kafka", "Docker", "Hibernate"],
      requirements: [
        "Коммерческий опыт разработки на Java от 4 лет",
        "Отличное владение Spring Framework (Boot, Data, Security, Cloud)",
        "Понимание принципов DDD, SOLID и шаблонов проектирования",
        "Технический английский от уровня Intermediate (B1/B2)",
      ],
      responsibilities: [
        "Проектирование API и интеграционных шлюзов",
        "Оптимизация производительности баз данных и запросов Hibernate",
        "Участие в Scrum-церемониях с зарубежными заказчиками",
      ],
      benefits: [
        "Офис в центре Самарканда или Ташкента, либо 100% Remote",
        "Полный социальный пакет и медицинская страховка",
        "Широкие возможности профессионального роста внутри EPAM Anywhere",
      ],
      sourceUrl: "https://epam.com/careers/java-developer-uz",
      sourceNormalizedUrl: "https://epam.com/careers/java-developer-uz",
      sourceName: "EPAM Careers",
      qualityScore: 94,
      relevanceScore: 95,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },

    // --- CLICK ---
    {
      title: "Product Designer (UI/UX) / Ведущий дизайнер",
      slug: "product-designer-ui-ux-click",
      companyId: companies["click-uz"].id,
      companyName: companies["click-uz"].name,
      description:
        "CLICK ищет продуктового дизайнера с сильным визуальным вкусом и пониманием поведения пользователей в мобильных приложениях. Вы будете отвечать за дизайн новых функций супераппа CLICK, проведение исследований и развитие дизайн-системы.",
      shortDescription: "Создание интерфейсов мобильного приложения CLICK для 10+ млн пользователей.",
      salaryMin: 15000000,
      salaryMax: 28000000,
      salaryCurrency: "UZS",
      salaryText: "15 000 000 – 28 000 000 сум",
      location: "Ташкент, Юнусабадский район",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["Figma", "UI/UX", "Mobile Design", "Design Systems", "Prototyping", "User Research"],
      requirements: [
        "Портфолио реализованных мобильных приложений (iOS/Android)",
        "Уверенное владение Figma (компоненты, автолейауты, переменные)",
        "Опыт проведения интервью с пользователями и юзабилити-тестирования",
      ],
      responsibilities: [
        "Проектирование пользовательских сценариев и экранов",
        "Поддержка и развитие дизайн-системы CLICK",
        "Контроль реализации дизайна разработчиками (Design Review)",
      ],
      benefits: [
        "Официальное оформление по ТК РУз",
        "Комфортный офис у метро Шахристан",
        "Оплата профильного обучения и подписок (Figma, Mobbin)",
      ],
      sourceUrl: "https://click.uz/vacancies/product-designer",
      sourceNormalizedUrl: "https://click.uz/vacancies/product-designer",
      sourceName: "CLICK Careers",
      qualityScore: 90,
      relevanceScore: 89,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Design",
    },
    {
      title: "Middle Android Developer (Kotlin / Coroutines)",
      slug: "middle-android-developer-kotlin-click",
      companyId: companies["click-uz"].id,
      companyName: companies["click-uz"].name,
      description:
        "Приглашаем Android разработчика в команду сервисов лояльности и платежей CLICK. Вас ждет чистая архитектура (MVVM / Clean Architecture), Kotlin Coroutines, Jetpack Compose и современные библиотеки платформы.",
      shortDescription: "Разработка мобильного приложения CLICK на Kotlin и Jetpack Compose.",
      salaryMin: 18000000,
      salaryMax: 30000000,
      salaryCurrency: "UZS",
      salaryText: "18 000 000 – 30 000 000 сум",
      location: "Ташкент",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["Android", "Kotlin", "Jetpack Compose", "Coroutines", "Dagger Hilt", "Room", "Git"],
      requirements: [
        "Опыт коммерческой Android разработки от 2.5 лет",
        "Уверенное знание Kotlin, Coroutines и Flow",
        "Опыт работы с Jetpack библиотеками (ViewModel, Room, Navigation)",
      ],
      responsibilities: [
        "Создание новых экранов и платежных модулей в приложении",
        "Рефакторинг и покрытие кода Unit-тестами",
        "Устранение багов и оптимизация энергопотребления",
      ],
      benefits: [
        "Стабильная заработная плата с регулярным пересмотром",
        "Обучение за счет компании и участие в митапах",
        "Бесплатные обеды и комфортный офис",
      ],
      sourceUrl: "https://click.uz/vacancies/android-developer",
      sourceNormalizedUrl: "https://click.uz/vacancies/android-developer",
      sourceName: "CLICK Careers",
      qualityScore: 92,
      relevanceScore: 93,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Mobile",
    },

    // --- TBC Bank Uzbekistan ---
    {
      title: "Senior Flutter Developer (Cross-platform Mobile)",
      slug: "senior-flutter-developer-tbc-bank",
      companyId: companies["tbc-bank-uz"].id,
      companyName: companies["tbc-bank-uz"].name,
      description:
        "TBC Bank Uzbekistan ищет ведущего кроссплатформенного разработчика на Flutter. Наше мобильное приложение — основной канал взаимодействия с клиентами банка. Мы ценим строгие стандарты качества кода, Clean Architecture, BLoC и надежность.",
      shortDescription: "Разработка ключевого мобильного банковского приложения TBC на Flutter.",
      salaryMin: 2200,
      salaryMax: 3600,
      salaryCurrency: "USD",
      salaryText: "$2,200 – $3,600",
      location: "Ташкент / Удаленно",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: true,
      skills: ["Flutter", "Dart", "BLoC", "Clean Architecture", "REST API", "CI/CD", "Security"],
      requirements: [
        "Опыт разработки на Flutter от 3 лет, общий опыт мобильной разработки от 5 лет",
        "Глубокое понимание State Management (BLoC / Cubit)",
        "Опыт работы с анимациями, кастомными Canvas и сложными UI компонентами",
        "Понимание нюансов работы с платежными системами и криптографией",
      ],
      responsibilities: [
        "Проектирование и разработка модулей кредитования, вкладов и карт",
        "Оптимизация производительности приложения на бюджетных смартфонах",
        "Наставничество Middle-разработчиков и проведение код-ревью",
      ],
      benefits: [
        "Международная культура TBC Group",
        "Высокая компенсация с привязкой к курсу доллара",
        "Гибкий гибридный график или полная удаленка",
      ],
      sourceUrl: "https://tbcbank.uz/careers/flutter-dev",
      sourceNormalizedUrl: "https://tbcbank.uz/careers/flutter-dev",
      sourceName: "TBC Careers",
      qualityScore: 97,
      relevanceScore: 98,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Mobile",
    },
    {
      title: "Senior Data Scientist / Credit Scoring & ML",
      slug: "senior-data-scientist-credit-scoring-tbc",
      companyId: companies["tbc-bank-uz"].id,
      companyName: companies["tbc-bank-uz"].name,
      description:
        "Приглашаем опытного специалиста по машинному обучению и анализу данных для разработки скоринговых моделей кредитования физических лиц и малого бизнеса, антифрод-систем и предиктивной аналитики оттока клиентов.",
      shortDescription: "Построение скоринговых моделей кредитования и риск-менеджмента в TBC.",
      salaryMin: 2500,
      salaryMax: 4200,
      salaryCurrency: "USD",
      salaryText: "$2,500 – $4,200",
      location: "Ташкент",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: false,
      skills: ["Python", "Machine Learning", "Credit Scoring", "LightGBM", "XGBoost", "SQL", "Airflow"],
      requirements: [
        "Опыт работы Data Scientist в банках или финтехе от 3 лет",
        "Отличное владение Python (pandas, numpy, scikit-learn, optuna)",
        "Опыт внедрения градиентного бустинга и валидации моделей (Gini, ROC-AUC, KS)",
        "Уверенный SQL для работы с сырыми транзакционными витринами",
      ],
      responsibilities: [
        "Разработка и мониторинг качества скоринговых карт",
        "Внедрение ML моделей в боевой микросервисный пайплайн (MAPI)",
        "Проведение когортного анализа и оценка финансового эффекта",
      ],
      benefits: [
        "Работа с терабайтами реальных финансовых транзакций",
        "Доступ к передовому аппаратному стеку и GPU кластерам",
        "Расширенная медицинская страховка",
      ],
      sourceUrl: "https://tbcbank.uz/careers/data-scientist",
      sourceNormalizedUrl: "https://tbcbank.uz/careers/data-scientist",
      sourceName: "TBC Careers",
      qualityScore: 96,
      relevanceScore: 97,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Data Science",
    },

    // --- Yandex Uzbekistan ---
    {
      title: "Senior Fullstack Developer (Node.js / React)",
      slug: "senior-fullstack-developer-yandex-uz",
      companyId: companies["yandex-uzbekistan"].id,
      companyName: companies["yandex-uzbekistan"].name,
      description:
        "Команда Yandex Uzbekistan развивает B2B платформы и сервис локализации продуктов для рынков Центральной Азии. Мы ищем разработчика полного стека для создания масштабируемых панелей управления партнерами, интеграционных API и высоконагруженных клиентских приложений.",
      shortDescription: "Создание B2B-платформ и сервисов Яндекса для Центральной Азии.",
      salaryMin: 2500,
      salaryMax: 4000,
      salaryCurrency: "USD",
      salaryText: "$2,500 – $4,000",
      location: "Ташкент, ул. Амира Темура",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: false,
      skills: ["TypeScript", "Node.js", "React", "Next.js", "PostgreSQL", "Docker", "REST API"],
      requirements: [
        "Опыт Fullstack разработки от 4 лет на современном JS/TS стеке",
        "Глубокое знание внутреннего устройства Node.js и React (хуки, concurrent mode)",
        "Понимание реляционных баз данных и механизмов индексации",
      ],
      responsibilities: [
        "Разработка надежных API и веб-интерфейсов для сотен тысяч партнеров",
        "Оптимизация производительности страниц и серверного рендеринга",
        "Участие в проектировании системной архитектуры",
      ],
      benefits: [
        "Трудоустройство в международной технологической компании",
        "Питание, ДМС с первого дня работы",
        "Опционные программы и ежегодные бонусы",
      ],
      sourceUrl: "https://yandex.uz/jobs/fullstack-tashkent",
      sourceNormalizedUrl: "https://yandex.uz/jobs/fullstack-tashkent",
      sourceName: "Yandex Jobs",
      qualityScore: 96,
      relevanceScore: 98,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },
    {
      title: "Lead ML Engineer (Computer Vision & NLP)",
      slug: "lead-ml-engineer-yandex-uz",
      companyId: companies["yandex-uzbekistan"].id,
      companyName: companies["yandex-uzbekistan"].name,
      description:
        "Ищем Lead ML инженера для адаптации моделей компьютерного зрения и обработки узбекского языка (NLP) в сервисах распознавания чеков, документов, картографических объектов и голосовых помощников.",
      shortDescription: "Разработка ML-моделей CV и NLP для узбекского языка в сервисах Яндекса.",
      salaryMin: 3000,
      salaryMax: 4800,
      salaryCurrency: "USD",
      salaryText: "$3,000 – $4,800",
      location: "Ташкент",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Lead",
      isRemote: false,
      skills: ["Python", "PyTorch", "NLP", "Computer Vision", "Transformers", "LLM", "CUDA"],
      requirements: [
        "Опыт в Machine Learning / Deep Learning от 5 лет",
        "Опыт обучения и файнтюнинга трансформерных моделей (LLaMA, Whisper, BERT)",
        "Понимание методов оптимизации инференса (TensorRT, ONNX, vLLM)",
      ],
      responsibilities: [
        "Руководство исследовательской и прикладной группой ML",
        "Разработка датасетов и метрик качества для узбекского языка",
        "Интеграция обученных моделей в боевой продакшн",
      ],
      benefits: [
        "Участие в знаковых национальных AI-инициативах",
        "Премиальный офис в центре Ташкента",
        "Высокий оклад в валюте и релокационная поддержка",
      ],
      sourceUrl: "https://yandex.uz/jobs/ml-lead-tashkent",
      sourceNormalizedUrl: "https://yandex.uz/jobs/ml-lead-tashkent",
      sourceName: "Yandex Jobs",
      qualityScore: 98,
      relevanceScore: 99,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Data Science",
    },

    // --- Beeline Uzbekistan ---
    {
      title: "DevOps & Linux System Administrator",
      slug: "devops-linux-sysadmin-beeline-uz",
      companyId: companies["beeline-uzbekistan"].id,
      companyName: companies["beeline-uzbekistan"].name,
      description:
        "Beeline ищет системного инженера / DevOps для поддержки корпоративной виртуализированной инфраструктуры, серверов биллинга и мониторинга высоконагруженных телеком-шлюзов.",
      shortDescription: "Администрирование Linux-инфраструктуры и серверов биллинга Beeline.",
      salaryMin: 14000000,
      salaryMax: 24000000,
      salaryCurrency: "UZS",
      salaryText: "14 000 000 – 24 000 000 сум",
      location: "Ташкент, Мирзо-Улугбекский район",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["Linux", "Bash", "Ansible", "Docker", "Zabbix", "Prometheus", "Nginx", "PostgreSQL"],
      requirements: [
        "Опыт работы системным администратором Linux от 3 лет",
        "Опыт написания плейбуков Ansible и Bash-скриптов",
        "Понимание стека TCP/IP, DNS, VPN, firewall (iptables)",
      ],
      responsibilities: [
        "Поддержка 24/7 доступности серверов и сервисов компании",
        "Автоматизация обновлений конфигураций с помощью Ansible",
        "Регулярное резервное копирование и участие в устранении сбоев",
      ],
      benefits: [
        "Официальное трудоустройство в крупной телеком-компании",
        "Корпоративная мобильная связь и скидки на домашний интернет",
        "Медицинская страховка",
      ],
      sourceUrl: "https://beeline.uz/careers/sysadmin",
      sourceNormalizedUrl: "https://beeline.uz/careers/sysadmin",
      sourceName: "Beeline Careers",
      qualityScore: 89,
      relevanceScore: 90,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "DevOps",
    },

    // --- Anorbank ---
    {
      title: "Senior Backend Engineer (Go / Microservices)",
      slug: "senior-backend-engineer-go-anorbank",
      companyId: companies["anorbank-uz"].id,
      companyName: companies["anorbank-uz"].name,
      description:
        "Цифровой банк Anorbank приглашает опытного Backend разработчика на Golang. В центре задач — развитие ядра необанка, интеграции с Национальным Межбанковским Процессинговым Центром (HUMO / UZCARD) и моментальные P2P переводы.",
      shortDescription: "Разработка ядра цифрового необанка Anorbank на Go и gRPC.",
      salaryMin: 2200,
      salaryMax: 3500,
      salaryCurrency: "USD",
      salaryText: "$2,200 – $3,500",
      location: "Ташкент",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: false,
      skills: ["Go", "Golang", "PostgreSQL", "gRPC", "Redis", "Kafka", "Docker", "Fintech"],
      requirements: [
        "Опыт разработки на Go от 3 лет в коммерческих проектах",
        "Опыт интеграции с платежными шлюзами и банковскими API",
        "Понимание принципов ACID, транзакционной изоляции и безопасной обработки платежей",
      ],
      responsibilities: [
        "Разработка масштабируемых микросервисов",
        "Проектирование безопасных контрактов взаимодействия (gRPC/protobuf)",
        "Оптимизация высоконагруженных SQL запросов к базе данных",
      ],
      benefits: [
        "Высокий уровень дохода с привязкой к доллару",
        "Удобный офис с панорамным видом на город",
        "Оплачиваемый отпуск 24 рабочих дня и ДМС",
      ],
      sourceUrl: "https://anorbank.uz/careers/backend-go",
      sourceNormalizedUrl: "https://anorbank.uz/careers/backend-go",
      sourceName: "Anorbank Careers",
      qualityScore: 95,
      relevanceScore: 96,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },
    {
      title: "Frontend Developer (Vue.js / Nuxt.js)",
      slug: "frontend-developer-vue-anorbank",
      companyId: companies["anorbank-uz"].id,
      companyName: companies["anorbank-uz"].name,
      description:
        "Ищем талантливого Frontend разработчика на Vue 3 и Nuxt 3 для развития публичного портала банка и веб-версии интернет-банкинга для юридических лиц.",
      shortDescription: "Создание интерфейсов интернет-банка на Vue 3 и Nuxt 3.",
      salaryMin: 14000000,
      salaryMax: 22000000,
      salaryCurrency: "UZS",
      salaryText: "14 000 000 – 22 000 000 сум",
      location: "Ташкент",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["Vue.js", "Nuxt.js", "JavaScript", "TypeScript", "Tailwind CSS", "Pinia"],
      requirements: [
        "Опыт разработки на Vue.js от 2 лет",
        "Уверенное понимание Composition API, Pinia и Nuxt 3",
        "Опыт адаптивной кроссбраузерной верстки",
      ],
      responsibilities: [
        "Разработка новых разделов интернет-банкинга",
        "Оптимизация скорости загрузки страниц и SEO",
        "Интеграция со сложными REST API",
      ],
      benefits: [
        "Официальное оформление с первого дня",
        "Квартальные премии по KPI",
        "Обучение и участие в профильных митапах",
      ],
      sourceUrl: "https://anorbank.uz/careers/frontend-vue",
      sourceNormalizedUrl: "https://anorbank.uz/careers/frontend-vue",
      sourceName: "Anorbank Careers",
      qualityScore: 91,
      relevanceScore: 92,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },

    // --- IT Park Uzbekistan ---
    {
      title: "Junior Web Developer (React / JavaScript)",
      slug: "junior-web-developer-it-park-bukhara",
      companyId: companies["it-park-uzbekistan"].id,
      companyName: companies["it-park-uzbekistan"].name,
      description:
        "Филиал IT Park в Бухаре открывает позицию для начинающего веб-разработчика. Отличный шанс начать карьеру в сфере IT: вы будете участвовать в разработке порталов для резидентов и образовательных платформ под руководством опытных менторов.",
      shortDescription: "Старт карьеры в IT: разработка веб-сервисов для резидентов IT Park Бухара.",
      salaryMin: 6000000,
      salaryMax: 10000000,
      salaryCurrency: "UZS",
      salaryText: "6 000 000 – 10 000 000 сум",
      location: "Бухара",
      city: "Бухара",
      employmentType: "Full-time",
      experienceLevel: "Junior",
      isRemote: false,
      skills: ["JavaScript", "React", "HTML/CSS", "Git", "Tailwind CSS", "REST API"],
      requirements: [
        "Базовые знания JavaScript (ES6+), HTML5, CSS3",
        "Опыт написания учебных или пет-проектов на React",
        "Умение работать с Git (GitHub/GitLab)",
        "Желание активно учиться и расти в команде",
      ],
      responsibilities: [
        "Верстка интерфейсов по макетам в Figma",
        "Разработка компонентов и подключение к API",
        "Исправление мелких багов под менторством Senior разработчика",
      ],
      benefits: [
        "Менторская программа и бесплатный доступ к курсам IT Academy",
        "Работа в современном коворкинге IT Park Бухара",
        "Карьерный рост до Middle разработчика за 1-1.5 года",
      ],
      sourceUrl: "https://it-park.uz/careers/junior-dev-bukhara",
      sourceNormalizedUrl: "https://it-park.uz/careers/junior-dev-bukhara",
      sourceName: "IT Park Careers",
      qualityScore: 88,
      relevanceScore: 89,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },
    {
      title: "Startup Acceleration & Community Manager",
      slug: "startup-acceleration-manager-it-park",
      companyId: companies["it-park-uzbekistan"].id,
      companyName: companies["it-park-uzbekistan"].name,
      description:
        "Ищем энергичного менеджера акселерационных программ в IT Park Самарканд. Задача — курировать стартапы ранних стадий, организовывать Demo Days, привлекать венчурные фонды и развивать стартап-сообщество региона.",
      shortDescription: "Управление акселерацией стартапов и развитие IT-сообщества в Самарканде.",
      salaryMin: 10000000,
      salaryMax: 16000000,
      salaryCurrency: "UZS",
      salaryText: "10 000 000 – 16 000 000 сум",
      location: "Самарканд",
      city: "Самарканд",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["Community Management", "Event Management", "Startup Acceleration", "Networking", "English"],
      requirements: [
        "Опыт работы в экосистеме стартапов, инкубаторах или проектном менеджменте от 2 лет",
        "Свободный узбекский и русский языки, английский на уровне уверенного общения",
        "Навыки публичных выступлений и организации масштабных мероприятий",
      ],
      responsibilities: [
        "Организация программ отбора стартапов в инкубаторы IT Park",
        "Координация трекеров, менторов и спикеров",
        "Помощь командам в подготовке инвестиционных питч-деков",
      ],
      benefits: [
        "Широчайшая сеть контактов с международными инвесторами",
        "Участие в глобальных технологических форумах",
        "Официальное оформление и бонусы",
      ],
      sourceUrl: "https://it-park.uz/careers/startup-manager",
      sourceNormalizedUrl: "https://it-park.uz/careers/startup-manager",
      sourceName: "IT Park Careers",
      qualityScore: 90,
      relevanceScore: 91,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Management",
    },

    // --- Billz ---
    {
      title: "Middle Backend Engineer (Node.js / NestJS)",
      slug: "middle-backend-engineer-billz",
      companyId: companies["billz-io"].id,
      companyName: companies["billz-io"].name,
      description:
        "SaaS компания Billz ищет инженера бэкенда для автоматизации кассовых узлов и облачного учета магазинов в Узбекистане и Казахстане. Стек: Node.js, NestJS, TypeScript, PostgreSQL, TypeORM, RabbitMQ.",
      shortDescription: "Разработка облачного SaaS бэкенда для ритейла на NestJS и PostgreSQL.",
      salaryMin: 1500,
      salaryMax: 2600,
      salaryCurrency: "USD",
      salaryText: "$1,500 – $2,600",
      location: "Ташкент / Удаленно",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: true,
      skills: ["Node.js", "NestJS", "TypeScript", "PostgreSQL", "RabbitMQ", "Docker", "Microservices"],
      requirements: [
        "Опыт разработки на Node.js / TypeScript от 2.5 лет",
        "Опыт работы с фреймворком NestJS и архитектурой микросервисов",
        "Понимание реляционных баз данных, транзакций и очередей сообщений",
      ],
      responsibilities: [
        "Разработка API для мобильного и веб-клиента кассового узла",
        "Интеграция с фискальными регистраторами и налоговыми шлюзами",
        "Оптимизация аналитических отчетов по продажам",
      ],
      benefits: [
        "Оклад в долларах США с защитой от инфляции",
        "Полная удаленная работа или стильный офис в Ташкенте",
        "Сильная инженерная культура без лишней бюрократии",
      ],
      sourceUrl: "https://billz.io/careers/backend-engineer",
      sourceNormalizedUrl: "https://billz.io/careers/backend-engineer",
      sourceName: "Billz Careers",
      qualityScore: 93,
      relevanceScore: 94,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },

    // --- Mad Devs Central Asia ---
    {
      title: "Golang Highload Engineer (Distributed Systems)",
      slug: "golang-highload-engineer-mad-devs",
      companyId: companies["mad-devs-ca"].id,
      companyName: companies["mad-devs-ca"].name,
      description:
        "Mad Devs ищет сильного Go разработчика для участия в сложных международных проектах. Задачи включают обработку потоковых данных в реальном времени, оптимизацию высоконагруженных сетевых протоколов и распределенный консенсус.",
      shortDescription: "Разработка распределенных высоконагруженных систем на Go.",
      salaryMin: 2400,
      salaryMax: 3800,
      salaryCurrency: "USD",
      salaryText: "$2,400 – $3,800",
      location: "Удаленно / Узбекистан",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: true,
      skills: ["Go", "Golang", "Distributed Systems", "gRPC", "PostgreSQL", "Kafka", "Docker"],
      requirements: [
        "Опыт разработки на Golang от 3.5 лет",
        "Понимание принципов построения распределенных систем (CAP-теорема, Raft/Paxos)",
        "Опыт профилирования и оптимизации CPU/Memory в высоконагруженных сервисах",
        "Английский на уровне свободного чтения и ведения переписки",
      ],
      responsibilities: [
        "Проектирование и разработка архитектуры сервисов с нуля",
        "Покрытие тестами (unit, integration, load tests)",
        "Участие в технических аудитах и open-source проектах компании",
      ],
      benefits: [
        "100% Remote формат работы из любой точки Узбекистана",
        "Оплата профильных курсов, конференций и сертификатов",
        "Прозрачная грейдовая сетка с пересмотром каждые 6 месяцев",
      ],
      sourceUrl: "https://maddevs.io/careers/golang",
      sourceNormalizedUrl: "https://maddevs.io/careers/golang",
      sourceName: "Mad Devs Careers",
      qualityScore: 96,
      relevanceScore: 97,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },

    // --- Exadel Uzbekistan ---
    {
      title: "Senior React / TypeScript Developer",
      slug: "senior-react-typescript-developer-exadel",
      companyId: companies["exadel-uzbekistan"].id,
      companyName: companies["exadel-uzbekistan"].name,
      description:
        "Exadel Uzbekistan приглашает Senior Frontend разработчика для работы на масштабном проекте цифровой трансформации для американского заказчика из сферы здравоохранения. Стек: React 18, TypeScript, Redux Toolkit, Webpack, Jest.",
      shortDescription: "Разработка enterprise веб-платформ на React и TypeScript в Exadel.",
      salaryMin: 2200,
      salaryMax: 3500,
      salaryCurrency: "USD",
      salaryText: "$2,200 – $3,500",
      location: "Самарканд / Remote",
      city: "Самарканд",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: true,
      skills: ["React", "TypeScript", "Redux Toolkit", "Jest", "CI/CD", "HTML/CSS", "English"],
      requirements: [
        "Опыт коммерческой разработки на React от 4 лет",
        "Глубокие знания TypeScript и строгой типизации",
        "Опыт покрытия приложений тестами (Jest, React Testing Library)",
        "Разговорный английский язык не ниже B2 (интервью на английском)",
      ],
      responsibilities: [
        "Разработка масштабируемых UI компонентов",
        "Коммуникация с распределенной международной командой разработки",
        "Участие в планировании спринтов и архитектурных сессиях",
      ],
      benefits: [
        "Официальный контракт с привязкой к доллару США",
        "Курсы английского языка внутри компании",
        "ДМС и компенсация спорта",
      ],
      sourceUrl: "https://exadel.com/careers/react-samarkand",
      sourceNormalizedUrl: "https://exadel.com/careers/react-samarkand",
      sourceName: "Exadel Careers",
      qualityScore: 94,
      relevanceScore: 95,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },
    {
      title: "Senior QA Automation Engineer (Python / Playwright)",
      slug: "senior-qa-automation-python-exadel",
      companyId: companies["exadel-uzbekistan"].id,
      companyName: companies["exadel-uzbekistan"].name,
      description:
        "Ищем Senior QA Automation инженера для построения фреймворка автоматизированного E2E и API тестирования. Вы будете внедрять автотесты в CI/CD пайплайны и обеспечивать стабильность релизов.",
      shortDescription: "Автоматизация E2E и API тестирования на Python и Playwright.",
      salaryMin: 1900,
      salaryMax: 3000,
      salaryCurrency: "USD",
      salaryText: "$1,900 – $3,000",
      location: "Самарканд / Удаленно",
      city: "Самарканд",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: true,
      skills: ["QA Automation", "Python", "Playwright", "Pytest", "Docker", "GitLab CI", "REST API"],
      requirements: [
        "Опыт в автоматизации тестирования от 3.5 лет на Python",
        "Практический опыт с Playwright / Selenium и Pytest",
        "Опыт тестирования RESTful API и интеграции тестов в CI/CD",
        "Английский язык на уровне B1/B2",
      ],
      responsibilities: [
        "Проектирование и поддержка фреймворка автотестов",
        "Анализ отчетов о прогонах и локализация дефектов",
        "Тесное взаимодействие с разработчиками для обеспечения тест-дизайна",
      ],
      benefits: [
        "Гибкий график и возможность 100% удаленной работы",
        "Ежегодный бонус за результативность",
        "Профессиональная сертификация (ISTQB) за счет компании",
      ],
      sourceUrl: "https://exadel.com/careers/qa-automation-uz",
      sourceNormalizedUrl: "https://exadel.com/careers/qa-automation-uz",
      sourceName: "Exadel Careers",
      qualityScore: 93,
      relevanceScore: 94,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "IT / Software",
    },

    // --- Kapitalbank ---
    {
      title: "Lead BI Analyst / Разработчик Power BI & SQL",
      slug: "lead-bi-analyst-kapitalbank",
      companyId: companies["kapitalbank-uz"].id,
      companyName: companies["kapitalbank-uz"].name,
      description:
        "Департамент финансовой аналитики и отчетности АКБ 'Капиталбанк' ищет ведущего BI-аналитика для создания интерактивных дашбордов для правления банка, моделирования хранилища данных (DWH) и финансового скоринга.",
      shortDescription: "Построение дашбордов Power BI и проектирование витрин DWH в Капиталбанке.",
      salaryMin: 16000000,
      salaryMax: 26000000,
      salaryCurrency: "UZS",
      salaryText: "16 000 000 – 26 000 000 сум",
      location: "Ташкент, Мирабадский район",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Senior",
      isRemote: false,
      skills: ["Power BI", "DAX", "SQL", "PostgreSQL", "DWH", "ETL", "Финансовый анализ"],
      requirements: [
        "Опыт работы BI-аналитиком / разработчиком от 3 лет, желательно в банковском секторе",
        "Продвинутое владение Power BI (DAX, Power Query, модели данных)",
        "Отличное знание сложных SQL запросов (оконные функции, CTE, оптимизация планов)",
      ],
      responsibilities: [
        "Проектирование аналитических витрин данных в корпоративном DWH",
        "Разработка и автоматизация регулярной управленческой отчетности",
        "Консультирование бизнес-подразделений по интерпретации данных",
      ],
      benefits: [
        "Стабильная работа в одном из крупнейших частных банков страны",
        "Годовые премии по результатам финансовых показателей банка",
        "Льготное банковское обслуживание и кредитование",
      ],
      sourceUrl: "https://kapitalbank.uz/careers/bi-analyst",
      sourceNormalizedUrl: "https://kapitalbank.uz/careers/bi-analyst",
      sourceName: "Kapitalbank Careers",
      qualityScore: 91,
      relevanceScore: 92,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Finance",
    },
    {
      title: "IT Account Manager / Менеджер по работе с корпоративными клиентами",
      slug: "it-account-manager-fergana-kapitalbank",
      companyId: companies["kapitalbank-uz"].id,
      companyName: companies["kapitalbank-uz"].name,
      description:
        "Приглашаем амбициозного менеджера по работе с корпоративными клиентами в филиал банка в г. Фергана. Вы будете привлекать предприятия к зарплатным проектам, интернет-эквайрингу, факторингу и торговым сервисам банка.",
      shortDescription: "Развитие корпоративных цифровых продуктов банка в Ферганской долине.",
      salaryMin: 10000000,
      salaryMax: 18000000,
      salaryCurrency: "UZS",
      salaryText: "10 000 000 – 18 000 000 сум",
      location: "Фергана",
      city: "Фергана",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["B2B Продажи", "Банковские продукты", "Переговоры", "Эквайринг", "CRM"],
      requirements: [
        "Опыт в активных B2B продажах или банковской сфере от 2 лет",
        "Отличные коммуникативные и презентационные навыки",
        "Знание специфики бизнеса в Ферганском регионе",
      ],
      responsibilities: [
        "Поиск и привлечение новых корпоративных клиентов в регионе",
        "Проведение встреч с первыми лицами компаний и презентация цифровых решений",
        "Выполнение планов по объемам эквайринга и зарплатных проектов",
      ],
      benefits: [
        "Базовый оклад + высокий % от привлеченных контрактов без потолка",
        "Компенсация мобильной связи и ГСМ",
        "Корпоративное обучение в Ташкенте",
      ],
      sourceUrl: "https://kapitalbank.uz/careers/account-manager-fergana",
      sourceNormalizedUrl: "https://kapitalbank.uz/careers/account-manager-fergana",
      sourceName: "Kapitalbank Careers",
      qualityScore: 89,
      relevanceScore: 90,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Sales",
    },

    // --- Ucell ---
    {
      title: "Инженер телекоммуникационных сетей (5G / LTE)",
      slug: "telecom-network-engineer-andijan-ucell",
      companyId: companies["ucell-uz"].id,
      companyName: companies["ucell-uz"].name,
      description:
        "Компания Ucell ищет инженера базовых станций и радиоподсистемы в Андижанской области для монтажа, пусконаладки и мониторинга оборудования сетей LTE и 5G.",
      shortDescription: "Развертывание и обслуживание базовых станций 4G/5G в Андижане.",
      salaryMin: 11000000,
      salaryMax: 17000000,
      salaryCurrency: "UZS",
      salaryText: "11 000 000 – 17 000 000 сум",
      location: "Андижан",
      city: "Андижан",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["Telecommunications", "LTE", "5G", "Radio Planning", "Huawei/ZTE", "IP Networking"],
      requirements: [
        "Высшее техническое образование в области телекоммуникаций или радиосвязи",
        "Опыт работы с оборудованием сотовой связи (Huawei, ZTE, Ericsson) от 2 лет",
        "Готовность к служебным выездам по Андижанской области",
      ],
      responsibilities: [
        "Контроль параметров радиосети (KPI) и устранение помех",
        "Проведение приемо-сдаточных испытаний новых базовых станций",
        "Взаимодействие с подрядными монтажными организациями",
      ],
      benefits: [
        "Служебный автомобиль или компенсация использования личного транспорта",
        "Бесплатная связь и медицинское страхование",
        "Работа в стабильной крупной компании",
      ],
      sourceUrl: "https://ucell.uz/careers/engineer-andijan",
      sourceNormalizedUrl: "https://ucell.uz/careers/engineer-andijan",
      sourceName: "Ucell Careers",
      qualityScore: 90,
      relevanceScore: 91,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Telecommunications",
    },

    // --- MyUztelecom ---
    {
      title: "Инженер инфраструктуры Дата-Центра (Data Center Specialist)",
      slug: "data-center-infrastructure-engineer-uztelecom",
      companyId: companies["uztelecom-uz"].id,
      companyName: companies["uztelecom-uz"].name,
      description:
        "Национальный оператор Uztelecom приглашает специалиста по эксплуатации инженерных систем ЦОД: систем гарантированного электропитания (ИБП, ДГУ), прецизионного кондиционирования, пожаротушения и СКС.",
      shortDescription: "Эксплуатация серверных помещений и инженерных систем ЦОД Uztelecom.",
      salaryMin: 13000000,
      salaryMax: 20000000,
      salaryCurrency: "UZS",
      salaryText: "13 000 000 – 20 000 000 сум",
      location: "Ташкент",
      city: "Ташкент",
      employmentType: "Full-time",
      experienceLevel: "Middle",
      isRemote: false,
      skills: ["Data Center", "СКС", "ИБП", "Климатические системы", "Мониторинг", "Серверы"],
      requirements: [
        "Опыт эксплуатации ЦОД или серверных узлов связи от 2 лет",
        "Понимание стандартов TIA-942 / Uptime Institute Tier II-III",
        "Группа допуска по электробезопасности не ниже III",
      ],
      responsibilities: [
        "Круглосуточный мониторинг параметров микроклимата и питания ЦОД",
        "Монтаж и коммутация серверного и телеком-оборудования в стойки",
        "Проведение планового технического обслуживания инженерных систем",
      ],
      benefits: [
        "Официальное трудоустройство в национальном операторе связи",
        "Сменный график работы или 5/2",
        "Социальные гарантии по коллективному договору",
      ],
      sourceUrl: "https://uztelecom.uz/careers/datacenter-engineer",
      sourceNormalizedUrl: "https://uztelecom.uz/careers/datacenter-engineer",
      sourceName: "Uztelecom Careers",
      qualityScore: 91,
      relevanceScore: 92,
      status: VacancyStatus.ACTIVE,
      isVerified: true,
      category: "Infrastructure",
    },
  ];

  for (const v of sampleVacancies) {
    await prisma.vacancy.upsert({
      where: { slug: v.slug },
      update: {
        title: v.title,
        companyId: v.companyId,
        companyName: v.companyName,
        description: v.description,
        shortDescription: v.shortDescription,
        salaryMin: v.salaryMin,
        salaryMax: v.salaryMax,
        salaryCurrency: v.salaryCurrency,
        salaryText: v.salaryText,
        location: v.location,
        city: v.city,
        employmentType: v.employmentType,
        experienceLevel: v.experienceLevel,
        isRemote: v.isRemote,
        skills: v.skills,
        requirements: v.requirements,
        responsibilities: v.responsibilities,
        benefits: v.benefits,
        sourceUrl: v.sourceUrl,
        sourceNormalizedUrl: v.sourceNormalizedUrl,
        sourceName: v.sourceName,
        qualityScore: v.qualityScore,
        relevanceScore: v.relevanceScore,
        status: v.status,
        isVerified: v.isVerified,
        category: v.category,
      },
      create: v,
    });
  }
  console.log(`💼 Successfully seeded ${sampleVacancies.length} comprehensive vacancies across Uzbekistan!`);

  console.log("✅ Database seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
